/**
 * Editorial content per Shopify product handle. Sourced from the real
 * product repos in iCloud (4in1ESC, 4in1ESC-30x30, OpenFC, OpenRX) —
 * NOT from the Shopify description field (which is currently a
 * placeholder). When a SKU gets real variants/metafields in Shopify
 * those take priority; this file fills the gaps the CMS doesn't cover.
 *
 * When you add a new product: add an entry keyed by the Shopify handle.
 * Missing entry = product renders with a minimal fallback layout.
 */

export type ChapterPin = {ref: string; part: string; cost?: string};

/**
 * Physical item that ships in the box. `qty` is free text so entries
 * can read "1×" or "kit" or "set". Keep items factual — only list
 * things that genuinely ship. No speculative filler.
 */
export type BoxItem = {qty?: string; item: string; note?: string};

/**
 * Downloadable asset rendered in the Downloads chapter. `kind` picks
 * the icon/label family; `href` can point anywhere — usually a file
 * in the product's GitHub repo (raw or releases), occasionally a
 * standalone CDN URL for heavy CAD.
 */
export type DownloadKind =
  | 'schematic'
  | 'step'
  | 'bom'
  | 'gerber'
  | 'manual'
  | 'wiring'
  | 'flash'
  | 'changelog'
  | 'sbom'
  | 'firmware_manifest'
  | 'other';

export type DownloadAsset = {
  kind: DownloadKind;
  label: string;
  href: string;
  note?: string;
  size?: string;
};

/**
 * Playful cross-sell card rendered under the buy strip. Use it to point
 * one product at another — e.g. OpenFC ↔ OpenESC both pointing at
 * OpenStack. Keep line copy short: it's a wink, not a paragraph.
 */
export type PairCta = {
  eyebrow: string;     // small uppercase line above (e.g. "PAIR WITH")
  title: string;       // main line (e.g. "OpenStack — FC + ESC, one solder-free stack")
  to: string;          // href to the paired product PDP
};

/**
 * A component of a bundle product (OpenStack et al). Each entry points
 * at an existing PDP and names the firmware that the component carries,
 * so the bundle PDP can render a "what's in the box" chapter without
 * duplicating editorial copy.
 */
export type BundleComponent = {
  title: string;
  handle: string;              // /products/<handle>
  firmware: string;            // "Betaflight", "AM32", etc.
  firmwareUrl?: string;
  blurb: string;               // one-liner used in the bundle card
};

/**
 * One tier in a product line. OpenRX (Lite/Lite-UFL/Mono/Gemini) and
 * OpenESC (20×20/30×30) are lines, not single products: the buyer picks
 * one tier on a comparison ladder that doubles as the variant selector.
 *
 * Editorial here is the source of truth for *which tiers exist and how
 * they differ*. The PDP cross-references the Shopify product's option
 * values (matched by `optionAxis` name + the key of this map) to wire
 * each card to a real, purchasable variant — price, stock, add-to-cart.
 * Until those Shopify variants exist the ladder still renders for preview
 * and the cart falls back to the single default variant.
 */
export type VariantContent = {
  /** Display name on the ladder card. Defaults to the variant key (which is
   *  what Shopify matches against); set this when the shown name should differ
   *  from the matched key (e.g. key "20×20" shown as "20×20 (mini)"). */
  label?: string;
  /** One-line role under the tier name in the ladder card. */
  tagline?: string;
  /** The 3–4 cells that differ between tiers, shown in the card body. */
  highlights: Array<[string, string]>;
  /** Per-tier spec deltas merged over the shared `specs` by row key: a
   *  value replaces the base row, `null` hides it (a cost-down tier dropping
   *  a sensor), and an unknown key appends. See `mergeSpecs` in the PDP. */
  specs?: Array<[string, string | null]>;
  /** Box lines specific to this tier, appended to the shared inTheBox. */
  inTheBox?: BoxItem[];
  /** Per-tier layered board SVG (same shape as `teardown.boardArt`). When the
   *  ladder selects this tier the teardown swaps to this art; tiers without
   *  their own art fall back to `teardown.boardArt`. Generated by
   *  `scripts/export-board-art.mjs <kicad_pcb> <handle>` — one handle per
   *  physical PCB (see scripts/boards.config.json). */
  boardArt?: {src: string; inspectUrl?: string; layers?: Record<string, string>};
  /** Per-tier exploded 3D model (same shape as `teardown.frameViewer`). The
   *  CAD analogue of `boardArt` for frames: the 3" and 5" tiers each carry
   *  their own GLB so the teardown viewer explodes the selected model. Tiers
   *  without their own model fall back to `teardown.frameViewer`. */
  frameViewer?: {src: string; inspectUrl?: string};
  /** When true the tier renders as a greyed, non-selectable "Coming soon"
   *  card — a designed model that is not yet a purchasable Shopify variant.
   *  It shows on the ladder for line completeness but can't be added to cart. */
  comingSoon?: boolean;
};

export type ProductContent = {
  fileNumber: string;           // "01" etc — shown in the eyebrow
  family: string;               // Category shown next to file number
  hero: {
    line1: string;
    line2Italic: string;        // middle line rendered in gold italic
    line3: string;
    lead: string;               // subhead paragraph in mono
  };
  firmware: {
    project: string;            // "AM32" / "Betaflight" / "ExpressLRS" / null
    projectUrl?: string;
    /** Optional project wordmark shown in the "The €1" chapter media slot
     *  (public path, e.g. `/logos/betaflight.svg`). Falls back to the
     *  geometric placeholder glyph when unset. */
    logo?: string;
    /** Set when the wordmark is white-on-transparent (e.g. AM32) so it gets
     *  rendered on a fixed dark tile that reads in both light and dark themes,
     *  instead of the transparent slot a multi-colour mark uses. */
    logoDark?: boolean;
  };
  repoUrl: string;
  teardown?: {
    title: string;
    body: string;
    pins: ChapterPin[];
    /** Optional layered SVG of the board, generated by
     *  `scripts/export-board-art.mjs <kicad_pcb> <handle>`. The component
     *  fetches `/boards/<handle>/board.svg`, inlines it, and reveals
     *  layers on scroll. Set `inspectUrl` to link out to KiCanvas's
     *  hosted viewer for users who want pan/zoom. */
    /** `layers` maps a copper-layer slug (`f`, `in1`…`in4`, `b`) to a short
     *  function blurb shown beside its name in the layer rail (e.g. "Ground
     *  plane", "Signal · 5V"). Optional — {@link BoardArt} falls back to a
     *  position-based guess (outer = signal+components, second = ground plane,
     *  middle = signal+power) when a slug is unset. */
    boardArt?: {src: string; inspectUrl?: string; layers?: Record<string, string>};
    /** Optional exploded 3D model — the CAD analogue of `boardArt`, for
     *  products that are an OnShape assembly rather than a KiCad board
     *  (the frame, later motors). `src` is a public GLB whose nodes follow
     *  the top/base/arm naming the {@link FrameViewer} explodes by; set
     *  `inspectUrl` to the public OnShape document. When present the
     *  teardown renders FrameViewer instead of BoardArt. */
    frameViewer?: {src: string; inspectUrl?: string};
  };
  inTheBox: BoxItem[];          // physical items shipped
  downloads: DownloadAsset[];   // schematic PDFs, STEP files, manuals, etc.
  specs: Array<[string, string]>;
  footnote?: string;            // appears under the family card
  /** When set, the PDP renders a comparison-ladder selector. `optionAxis`
   *  is the Shopify option NAME that carries the line's variants
   *  (standardised to "Model"); `variants` is keyed by the option VALUE. See
   *  {@link VariantContent}. */
  optionAxis?: string;
  variants?: Record<string, VariantContent>;
  pairCta?: PairCta;            // playful cross-sell under the buy strip
  bundle?: {                    // when set, the PDP renders as a bundle
    components: BundleComponent[];
  };
};

export const PRODUCT_CONTENT: Record<string, ProductContent> = {
  openesc: {
    fileNumber: '01',
    family: '4-in-1 ESC',
    hero: {
      line1: 'An ESC (or 4)',
      line2Italic: '',
      line3: '',
      lead:
        "6 mosfets per motor, 2 for each phase. Driven by a gate driver, controlled by a microcontroller. Duplicate that 4 times et voila, 'An ESC'.",
    },
    firmware: {
      project: 'AM32',
      projectUrl:
        'https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware',
      logo: '/logos/am32.svg',
      logoDark: true,
    },
    repoUrl: 'https://github.com/incutec-hw/OpenESC_20X20',
    teardown: {
      title: "Isn't it beautiful?",
      body:
        'ESCs have to carry a lot of current so optimized power routing matters. You can see it right here or check the interactive KiCad viewer. Each AT32 microcontroller is running AM32. A large array of low-ESR, high-capacitance ceramic capacitors feeds the fast switching of the MOSFETs to reduce voltage spikes. TVS diodes clamp any spikes that still get too high.',
      pins: [
        {ref: '①', part: 'AT32F421 MCU', cost: '×4'},
        {ref: '②', part: 'NSG2065Q gate driver', cost: '×4'},
        {ref: '③', part: 'Low Rds(on) MOSFET', cost: '×24'},
        {ref: '④', part: 'INA186A3 high-side current sense', cost: '×1'},
      ],
      boardArt: {
        src: '/boards/openesc/board.svg',
        inspectUrl:
          'https://kicanvas.org/?github=https://github.com/incutec-hw/OpenESC_20X20',
        layers: {
          f: 'Signal + components',
          in1: 'Ground plane',
          in2: 'Signal · 10V · 3V3',
          in3: 'Signal',
          in4: 'Ground plane',
          b: 'Signal + components',
        },
      },
    },
    inTheBox: [
      {qty: '1×', item: 'OpenESC'},
      {qty: '2×', item: '8-pin JST cable'},
      {qty: '1×', item: 'XT battery pigtail'},
      {qty: '4×', item: 'M3 grommets'},
      {qty: '1×', item: 'Low-ESR Electrolytic Capacitor'},
    ],
    // TODO(downloads): publish schematic.pdf, bom.csv, gerbers.zip, manual.pdf,
    // wiring.pdf, flashing.md to the OpenESC_20X20 repo and re-add the cards.
    // The KiCanvas viewer above + the GitHub link cover "study the design"
    // until the release artifacts ship.
    downloads: [],
    specs: [
      ['Firmware', 'AM32'],
      ['Protocol', 'DShot · bidirectional DShot telemetry · PWM'],
      ['Input', '3–6S LiPo (11.1–25.2 V)'],
      ['MCU', 'AT32F421G8U7, 120 MHz'],
      ['Gate driver', 'NSG2065Q (QFN-24)'],
      ['Current sense', 'INA186A3 high-side, board-level'],
      ['Power rails', 'LMR54406DBVR buck + TLV76733 LDO'],
      ['Connector', 'JST SM08B-SRSS-TB (8-pin BF)'],
      ['License', 'CERN-OHL-S-2.0'],
    ],
    // Launching with the 20×20 and 30×30 models. Pro (higher-current)
    // variants land later as additional values on the same "Model" axis.
    optionAxis: 'Model',
    variants: {
      '20×20': {
        highlights: [
          ['Mount', '20×20'],
          ['MOSFET', 'DOY180N03T'],
          ['Continuous', '30 A / channel*'],
        ],
        specs: [
          ['Continuous', '30 A / channel — preliminary, bench characterization pending'],
          ['MOSFETs', 'DOY180N03T, 30 V / 1.0 mΩ'],
          ['Input', '3–6S LiPo — 6S hard maximum (30 V FETs, TVS-clamped)'],
          ['Current sense', 'INA186A3 + 0.2 mΩ shunt · 20 mV/A, 165 A full-scale'],
          ['PCB', '6-layer, 2 oz outer copper, 20×20 mount'],
        ],
      },
      '30×30': {
        highlights: [
          ['Mount', '30×30'],
          ['MOSFET', 'SP40N01GHNK'],
          ['Continuous', '50 A / channel*'],
        ],
        specs: [
          ['Continuous', '50 A / channel — preliminary, bench characterization pending'],
          ['MOSFETs', 'SP40N01GHNK, 40 V / 1.2 mΩ'],
          ['Current sense', 'INA186A3 + 2× 0.2 mΩ shunt · 10 mV/A, 330 A full-scale'],
          ['PCB', '6-layer, 30×30 mount'],
        ],
        boardArt: {
          src: '/boards/openesc-30x30/board.svg',
          inspectUrl:
            'https://kicanvas.org/?github=https://github.com/incutec-hw/OpenESC-30x30',
          layers: {
            f: 'Signal + components',
            in1: 'Ground plane',
            in2: 'Signal · 10V · 3V3',
            in3: 'Signal',
            in4: 'Ground plane',
            b: 'Signal + components',
          },
        },
      },
    },
    pairCta: {
      eyebrow: 'Better together',
      title: 'OpenStack — board on board, zero solder, one checkout.',
      to: '/products/openstack',
    },
  },

  openfc: {
    fileNumber: '02',
    family: 'Flight Controller',
    hero: {
      line1: 'A flight controller',
      line2Italic: 'is mostly',
      line3: 'an IMU and a radio.',
      lead:
        'RP2354B dual-core M33 running Betaflight, a TDK-Invensense LSM6DSV16X IMU, barometer, blackbox flash, and a break-off 2.4 GHz ExpressLRS receiver on the same PCB. Snap the RX off when you want to mount it elsewhere.',
    },
    firmware: {
      project: 'Betaflight',
      projectUrl: 'https://github.com/betaflight/betaflight',
      logo: '/logos/betaflight.svg',
    },
    repoUrl: 'https://github.com/incutec-hw/OpenFC',
    teardown: {
      title: 'An MCU, an IMU, a radio, and enough UARTs for the rest.',
      body:
        'The RP2354B carries 520 KB of SRAM, integrated flash, and two PIO blocks. One PIO drives the analog OSD (opamp + mux detect the video syncs and switch between white and black pixels); the other provides two extra software UARTs. The ELRS module is a physical break-off on the same board — snap it off or fly with it attached.',
      pins: [
        {ref: '①', part: 'RP2354B — dual M33 @ 150 MHz'},
        {ref: '②', part: 'LSM6DSV16XTR IMU'},
        {ref: '③', part: 'BMP388 barometer'},
        {ref: '④', part: 'BY25Q128AS — 128 Mbit blackbox'},
        {ref: '⑤', part: 'Break-off ESP32-C3 ELRS RX'},
      ],
    },
    inTheBox: [
      {qty: '1×', item: 'OpenFC board', note: 'break-off 2.4 GHz ELRS RX attached; snap off if you want to relocate it'},
      {qty: '1×', item: '8-pin Betaflight signal cable', note: 'JST SM08B-SRSS-TB, pre-crimped, FC → ESC'},
      {qty: '1×', item: 'DJI/HD camera pigtail', note: 'JST-SH1.0 6-pin ↔ GHR 10-pin'},
      {qty: '4×', item: 'M3 rubber soft-mount grommets'},
      {qty: '1×', item: 'Build card', note: 'batch ID, QC initials, firmware flash command, GitHub rev'},
    ],
    downloads: [
      {
        kind: 'schematic',
        label: 'Schematic (PDF)',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/hardware/schematic.pdf',
        note: 'MCU, IMU, baro, blackbox, break-off RX sub-sheet',
      },
      {
        kind: 'step',
        label: '3D STEP',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/hardware/board.step',
        note: 'Board with RX attached (before snap-off)',
      },
      {
        kind: 'bom',
        label: 'BOM (CSV)',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/hardware/bom.csv',
      },
      {
        kind: 'gerber',
        label: 'Gerbers (ZIP)',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/hardware/gerbers.zip',
      },
      {
        kind: 'manual',
        label: 'User manual (PDF)',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/docs/manual.pdf',
      },
      {
        kind: 'wiring',
        label: 'Wiring diagram (PDF)',
        href: 'https://github.com/incutec-hw/OpenFC/raw/main/docs/wiring.pdf',
        note: 'ESC, VTX, camera, RX, motor LEDs',
      },
      {
        kind: 'flash',
        label: 'Betaflight target + flash guide',
        href: 'https://github.com/incutec-hw/OpenFC/blob/main/docs/flashing.md',
      },
    ],
    specs: [
      ['Firmware', 'Betaflight'],
      ['MCU', 'RP2354B (dual M33 @ 150 MHz)'],
      ['IMU', 'LSM6DSV16XTR'],
      ['Barometer', 'BMP388'],
      ['Blackbox', 'BY25Q128AS (16 MB)'],
      ['Motor outputs', '4× PWM / DShot'],
      ['RX', 'Break-off 2.4 GHz ExpressLRS'],
      ['OSD', 'Analog, PIO-driven (software WIP)'],
      ['UARTs', '2 hardware + 2 PIO'],
      ['USB', 'USB-C (config + flash)'],
      ['Power', '2–6S, 12 V switchable + 5 V'],
      ['Extras', '16 corner LEDs, buzzer, LED strip out'],
      ['License', 'CERN-OHL-S-2.0'],
    ],
    footnote:
      'The ELRS receiver break-off lets you relocate the RX without cutting traces. Solder onto the pads when reattaching.',
    // The full OpenFC (onboard ELRS break-off, barometer, SPI blackbox flash,
    // corner LEDs) is still in development — shown here as greyed "Coming soon"
    // cards in both mount sizes. The shipping cost-down board is a separate
    // product, OpenFC Lite (see the `openfc-lite` entry below).
    optionAxis: 'Model',
    variants: {
      'OpenFC Mini': {
        tagline: 'The full OpenFC on the 20×20 / 30.5 mount.',
        highlights: [
          ['Mount', '20×20 · 30.5 holes'],
          ['Radio', 'Onboard ELRS break-off'],
        ],
        comingSoon: true,
      },
      OpenFC: {
        tagline: 'The full OpenFC on the 30×30 mount.',
        highlights: [
          ['Mount', '30×30'],
          ['Radio', 'Onboard ELRS break-off'],
        ],
        comingSoon: true,
      },
    },
    pairCta: {
      eyebrow: 'Better together',
      title: 'OpenStack — OpenFC + OpenESC, one 30.5 mm stack, one checkout.',
      to: '/products/openstack',
    },
  },

  // The shipping cost-down flight controller. One design, two mount sizes
  // (20×20 / 30×30) that share nearly the whole BOM. Spec drawn from the
  // OpenFC-Lite / OpenFC-Lite-Mini READMEs. The Shopify product
  // (handle `openfc-lite`, Model: "20×20" / "30×30") is ACTIVE — this is the
  // live FC PDP; the old `openfc` product is archived in Shopify.
  'openfc-lite': {
    fileNumber: '02',
    family: 'Flight Controller',
    hero: {
      line1: 'A flight controller,',
      line2Italic: 'minus',
      line3: 'what you don’t need.',
      lead:
        'An RP2354 dual-core M33 running Betaflight on a 6-layer board: a 6-axis IMU, microSD blackbox, PIO-driven analog OSD (in development), and a switchable 10 V VTX rail. No barometer, no onboard radio — bring your own RX over UART and keep the board small and cheap.',
    },
    firmware: {
      project: 'Betaflight',
      projectUrl: 'https://github.com/betaflight/betaflight',
      logo: '/logos/betaflight.svg',
    },
    repoUrl: 'https://github.com/incutec-hw/OpenFC-Lite',
    teardown: {
      title: 'Two PIO blocks doing the work of a fistful of chips.',
      body:
        'The RP2354 has no analog-OSD peripheral and only two hardware UARTs, so its PIO blocks fake both. One drives the analog OSD front end — a comparator strips the video sync, an op-amp buffers the camera signal, and an SPDT switch injects black and white pixels — while another spins up extra software UARTs. The IMU and the microSD blackbox sit on separate SPI buses, and a switchable 10 V buck feeds the VTX and camera.',
      pins: [
        {ref: '①', part: 'RP2354 — dual M33 @ 150 MHz'},
        {ref: '②', part: '6-axis IMU (LGA-14, TDK/ST)'},
        {ref: '③', part: 'microSD blackbox, on SPI'},
        {ref: '④', part: 'Analog OSD — comparator + op-amp + SPDT'},
        {ref: '⑤', part: 'Switchable 10 V VTX buck'},
      ],
      // boardArt is supplied per variant (openfc-lite-mini / openfc-lite); the
      // PDP swaps the layer reveal as the ladder selects a mount size.
    },
    inTheBox: [
      {qty: '1×', item: 'OpenFC Lite board'},
      {qty: '1×', item: '8-pin JST SH ESC harness'},
      {qty: '4×', item: 'M3 rubber soft-mount grommets'},
      {qty: '1×', item: 'Build card', note: 'batch ID, QC initials, firmware flash command, GitHub rev'},
    ],
    // TODO(downloads): publish schematic.pdf / bom.csv / gerbers.zip / manual.pdf
    // to the OpenFC-Lite repos and wire the cards here.
    downloads: [],
    specs: [
      ['Firmware', 'Betaflight — custom RP2350 target, upstreaming in progress'],
      ['MCU', 'RP2354 — dual M33 @ 150 MHz, 2 MB flash'],
      ['IMU', 'ST LSM6DSV16X on SPI — LGA-14 footprint also takes TDK ICM-426xx'],
      ['Blackbox', 'microSD card (TF-021B)'],
      ['OSD', 'Analog, PIO-driven — in development; digital OSD via MSP DisplayPort'],
      ['Motor outputs', '4× DShot, bidirectional telemetry'],
      ['RX', 'External, over UART (CRSF/SBUS)'],
      ['Power', '3S–6S; switchable 10 V + always-on 5 V (3 A-rated bucks)'],
      ['USB', 'USB-C (config + UF2 flash)'],
      ['Layers', '6'],
      ['License', 'CERN-OHL-S-2.0'],
    ],
    footnote:
      'The cost-down trims over the full OpenFC: no barometer, no onboard radio, no SPI blackbox flash. External RX over UART, microSD for blackbox.',
    optionAxis: 'Model',
    variants: {
      '20×20': {
        tagline: 'The 20×20 mount — RP2354A, QFN-60. The compact stack size.',
        highlights: [
          ['Mount', '20×20'],
          ['Size', '20×20 mm'],
        ],
        specs: [
          ['MCU', 'RP2354A — dual M33 @ 150 MHz, QFN-60 (30 GPIO)'],
          ['Betaflight target', 'OPENFC_LITE_MINI_RP2350A'],
          ['UARTs', '3 — 2 hardware + 1 PIO'],
          ['Size', '20×20 mm, 6-layer'],
        ],
        boardArt: {
          src: '/boards/openfc-lite-mini/board.svg',
          inspectUrl:
            'https://kicanvas.org/?github=https://github.com/incutec-hw/OpenFC-Lite-Mini',
        },
      },
      '30×30': {
        tagline: 'The 30×30 mount — bigger pads and more I/O.',
        highlights: [
          ['Mount', '30×30'],
          ['Size', '30.5×30.5 mm'],
        ],
        specs: [
          ['UARTs', '4 — 2 hardware + 2 PIO'],
          ['Size', '30.5×30.5 mm, 6-layer'],
        ],
        boardArt: {
          src: '/boards/openfc-lite/board.svg',
          inspectUrl:
            'https://kicanvas.org/?github=https://github.com/incutec-hw/OpenFC-Lite',
        },
      },
    },
    pairCta: {
      eyebrow: 'Better together',
      title: 'OpenStack — OpenFC + OpenESC, one 30.5 mm stack, one checkout.',
      to: '/products/openstack',
    },
  },

  openrx: {
    fileNumber: '03',
    family: 'ELRS Receiver',
    hero: {
      line1: 'An ExpressLRS receiver,',
      line2Italic: 'open',
      line3: 'from antenna to firmware.',
      lead:
        'Four board designs, one firmware. Lite runs SX1281 on 2.4 GHz with a ceramic antenna. Lite-UFL swaps to a U.FL pigtail. Mono steps up to a single LR1121 for multi-band. Gemini runs dual LR1121 in ExpressLRS Xrossband mode for frequency-diverse links.',
    },
    firmware: {
      project: 'ExpressLRS',
      projectUrl: 'https://github.com/ExpressLRS/ExpressLRS',
    },
    repoUrl: 'https://github.com/incutec-hw/OpenRX',
    teardown: {
      title: 'One ESP32-C3, one (or two) radios, careful RF.',
      body:
        'Every variant runs on the ESP32-C3 at the MCU layer. Lite uses Semtech SX1281 with the 2450FM07D0034 BPF; Mono and Gemini use Semtech LR1121 with the RFX2401C + SKY13373 + Johanson IPD front-end. Firmware targets upstream to ExpressLRS (Unified_ESP32C3_2400_RX for Lite, Unified_ESP32C3_LR1121_RX for Mono/Gemini).',
      pins: [
        {ref: '①', part: 'ESP32-C3 — Wi-Fi OTA + CRSF'},
        {ref: '②', part: 'SX1281 (Lite) or LR1121 (Mono/Gemini)'},
        {ref: '③', part: 'RFX2401C + SKY13373 front-end (Mono/Gemini)'},
        {ref: '④', part: 'U.FL or ceramic antenna'},
      ],
    },
    inTheBox: [
      {qty: '1×', item: 'OpenRX board', note: 'tier selected at checkout'},
      {qty: '1×', item: 'CRSF servo cable', note: '3-pin JST-SH1.0, pre-crimped, 10 cm'},
      {qty: '1×', item: 'Heat-shrink sleeve + double-sided tape'},
      {qty: '1×', item: 'Build card', note: 'batch ID, QC initials, ExpressLRS flash target, GitHub rev'},
    ],
    // TODO(downloads): every previous card 404'd — the artifacts were never
    // published to the OpenRX repo. Publish schematic.pdf / boards.step /
    // bom.csv / gerbers.zip / manual.pdf / flashing.md, then re-add the cards.
    downloads: [],
    specs: [
      ['Firmware', 'ExpressLRS (3.5.0+)'],
      ['Telemetry', 'CRSF'],
      ['MCU', 'ESP32-C3, 4 MB flash'],
      ['Wi-Fi antenna', 'Dedicated on-board ceramic — separate from the link antenna'],
      ['Flashing', 'UART first, then Wi-Fi OTA / BF passthrough'],
      ['License', 'CERN-OHL-S-2.0'],
    ],
    optionAxis: 'Model',
    variants: {
      Lite: {
        tagline: 'SX1281 on 2.4 GHz with an on-board ceramic antenna — the low-cost default.',
        highlights: [
          ['Radio', 'Semtech SX1281'],
          ['Band', '2.4 GHz'],
          ['Antenna', 'Ceramic, on-board'],
        ],
        specs: [
          ['Radio', 'Semtech SX1281, 2.4 GHz'],
          ['Flash target', 'Unified_ESP32C3_2400_RX'],
          ['Telemetry power', '13 dBm (~20 mW)'],
          ['Antenna', 'On-board ceramic chip — no antenna wire to tear off'],
          ['Size', '10.05 × 10.55 mm, 6-layer'],
        ],
        boardArt: {src: '/boards/openrx-lite/board.svg'},
      },
      'Lite-UFL': {
        tagline: 'Same SX1281 radio, swapped to a U.FL pigtail for an external antenna.',
        highlights: [
          ['Radio', 'Semtech SX1281'],
          ['Band', '2.4 GHz'],
          ['Antenna', 'U.FL × 1'],
        ],
        specs: [
          ['Radio', 'Semtech SX1281, 2.4 GHz'],
          ['Flash target', 'Unified_ESP32C3_2400_RX'],
          ['Telemetry power', '13 dBm (~20 mW)'],
          ['Antenna', 'U.FL — run the dipole of your choice'],
          ['Size', '10.05 × 10.55 mm, 6-layer'],
        ],
        inTheBox: [{qty: '1×', item: 'U.FL dipole antenna'}],
        boardArt: {src: '/boards/openrx-lite-ufl/board.svg'},
      },
      Mono: {
        tagline: 'Single LR1121 for multi-band links, with the RF front-end.',
        highlights: [
          ['Radio', 'Semtech LR1121'],
          ['Band', '2.4 GHz + sub-GHz'],
          ['Front-end', 'RFX2401C + SKY13373'],
          ['Antenna', 'U.FL × 1'],
        ],
        specs: [
          ['Radio', 'Semtech LR1121 — dual-band from one antenna'],
          ['Flash target', 'Unified_ESP32C3_LR1121_RX'],
          ['Telemetry power', '12–22 dBm selectable (~158 mW max), 12 dB RX LNA'],
          ['Antenna', 'U.FL, both bands through one RF switch'],
          ['Size', '10.05 × 16.35 mm, 6-layer'],
        ],
        inTheBox: [{qty: '1×', item: 'U.FL dipole antenna'}],
        boardArt: {src: '/boards/openrx-mono/board.svg'},
      },
      Gemini: {
        tagline: 'Dual LR1121 in ExpressLRS Xrossband mode for frequency-diverse links.',
        highlights: [
          ['Radio', 'Semtech LR1121 × 2'],
          ['Band', '2.4 GHz + sub-GHz, diversity'],
          ['Front-end', 'RFX2401C + SKY13373'],
          ['Antenna', 'U.FL × 2'],
        ],
        specs: [
          ['Radio', '2× Semtech LR1121 — two complete radio chains'],
          ['Flash target', 'Unified_ESP32C3_LR1121_RX'],
          ['Telemetry power', '12–22 dBm per radio (~158 mW), 12 dB RX LNA per chain'],
          ['Antenna', '2× U.FL — one per radio'],
          ['Flashing', 'UART with on-board BOOT button, Wi-Fi OTA, BF passthrough'],
          ['Size', '17.05 × 15.75 mm, 6-layer'],
        ],
        inTheBox: [
          {qty: '2×', item: 'U.FL dipole antenna', note: 'diversity pair'},
        ],
        boardArt: {src: '/boards/openrx-gemini/board.svg'},
      },
    },
  },

  openframe: {
    fileNumber: '04',
    family: 'Carbon Frame',
    hero: {
      line1: 'The body',
      line2Italic: 'the rest',
      line3: 'bolts into.',
      lead:
        'CNC carbon-fibre freestyle frame on a 30.5×30.5 stack pattern. Designed in-house and OEM-built to start, with our own machining planned for 2027. OpenFC and OpenESC drop in without spacers.',
    },
    firmware: {
      project: '—',
    },
    repoUrl: 'https://github.com/incutec-hw',
    // TODO(copy): placeholder teardown editorial. The exploded viewer is the
    // CAD analogue of the boards' KiCanvas layer reveal; pin text reflects
    // only known specs (5 mm arms, 30.5 × 30.5 pattern) — no invented
    // material grades. inspectUrl omitted until the OnShape doc is public.
    teardown: {
      title: 'It comes apart the way it goes together.',
      body: '',
      pins: [
        {ref: '①', part: 'Top plate — carbon, carries the camera + VTX bay'},
        {ref: '②', part: 'Arms — 5 mm carbon, replaced individually', cost: '×4'},
        {ref: '③', part: 'Bottom plate — 30.5 × 30.5 stack pattern'},
        {ref: '④', part: 'M3 aluminium standoffs + hardware kit'},
      ],
      // Fallback model when a tier defines none. Both tiers (3"/5") override
      // this, so it also seeds the viewer's preload set — point it at a current
      // model (the 5") rather than the stale generic frame.glb.
      frameViewer: {
        src: '/models/frame5.glb',
      },
    },
    inTheBox: [
      {qty: '1×', item: 'Top plate + bottom plate'},
      {qty: '4×', item: '5" arms'},
      {qty: '1×', item: 'Hardware kit'},
      {qty: '1×', item: 'Camera mount'},
      {qty: '1×', item: 'VTX antenna tube clamp'},
      {qty: '1×', item: 'Build card'},
    ],
    // TODO(onshape): the frame is an OnShape document, not a GitHub repo. The
    // STEP/DXF/assembly links above were placeholders pointing at a non-existent
    // GitHub repo and have been removed. Wire real artifacts (OnShape embedded
    // viewer + STEP export) once the OnShape integration lands. We do not
    // release DXF cutting files.
    downloads: [],
    specs: [
      ['Arm thickness', '5 mm carbon'],
      ['Camera', '19 mm micro'],
      ['VTX bay', '20 × 20'],
      ['Video systems', 'Analog · DJI O3/O4 · Walksnail · HDZero'],
    ],
    footnote:
      "We're looking into setting up our own in-house machining for 2027.",
    // TODO(copy): placeholder variant editorial — wires the "Model" axis +
    // ladder. Shared specs above still read 5-inch; reconcile once the 3"
    // (OpenFrame3) specs land.
    optionAxis: 'Model',
    variants: {
      '5" Freestyle': {
        tagline: '',
        highlights: [
          ['Stack mounts', '20×20 · 25×25 · 30×30'],
          ['Motor mount', '16×16 · 19×19 (M3)'],
        ],
        frameViewer: {src: '/models/frame5.glb'},
      },
      '3" Freestyle': {
        tagline: '',
        highlights: [
          ['Stack mounts', '20×20 · 25×25'],
          ['Motor mount', '9×9 · 12×12 (M2)'],
        ],
        frameViewer: {src: '/models/frame3.glb'},
      },
    },
  },

  openstack: {
    fileNumber: '05',
    family: 'FC + ESC',
    hero: {
      line1: 'Not a product.',
      line2Italic: 'Just',
      line3: 'an FC and an ESC.',
      lead:
        'The stack is OpenFC-Lite and OpenESC bought together. Order each board on its own page and you get the exact same two boards — same hardware, same box, same firmware. Bundling changes one thing: one checkout instead of two, and the second courier saved. Betaflight and AM32 each still get their €1.',
    },
    // Firmware set to empty so the single-project €N+€1 chapter is
    // suppressed. The bundle chapter replaces it with a per-component
    // breakdown and shows the double contribution explicitly.
    firmware: {
      project: '',
    },
    repoUrl: 'https://github.com/incutec-hw',
    // No bundle-only items: the stack ships exactly what the two boards ship
    // in their own boxes — anything else would be a fiction, since buying
    // them separately gives the identical hardware. Each line points back to
    // the board whose box it comes from.
    inTheBox: [
      {qty: '1×', item: 'OpenFC-Lite board', note: 'ships in its own box — ESC harness, grommets, build card'},
      {qty: '1×', item: 'OpenESC board', note: 'ships in its own box — JST cables, XT pigtail, low-ESR cap, grommets'},
    ],
    // No combined "OpenStack" repo exists — there is no stack hardware. The
    // schematics, STEP and flashing docs live in each board's own repo; the
    // bundle cards below link straight to those PDPs.
    downloads: [],
    specs: [
      ['Includes', 'OpenFC-Lite + OpenESC'],
      ['Mount', '20×20 or 30×30 — matched pair'],
      ['FC firmware', 'Betaflight (RP2354)'],
      ['ESC firmware', 'AM32 (AT32F421 × 4)'],
      ['Continuous', '30 A (20×20) / 50 A (30×30) per channel — preliminary'],
      ['Input', '3–6S LiPo'],
      ['Harness', '8-pin JST SH, plug-and-play FC↔ESC — no signal soldering'],
      ['Contribution', '€1 → Betaflight, €1 → AM32'],
      ['License', 'CERN-OHL-S-2.0'],
    ],
    footnote:
      'Same two boards as their own pages — OpenFC-Lite + OpenESC, at the same prices. One checkout, one parcel, one courier fee instead of two. Firmware splits stay intact — Betaflight and AM32 each get their €1.',
    // Two stack sizes, picked on the same "Model" axis the FC and ESC use.
    // Each tier is just the matching pair at that mount size — the bundle
    // component handles don't change, only which size variant of each board
    // ships. Spec deltas describe the pair per size.
    optionAxis: 'Model',
    variants: {
      '20×20': {
        label: '20×20 (mini)',
        tagline: 'OpenFC-Lite-Mini + OpenESC 20×20 — sub-3", cinewhoop, micro.',
        highlights: [
          ['Pair', 'FC-Lite-Mini + ESC 20×20'],
          ['Mount', '20×20'],
          ['Continuous', '30 A / channel'],
        ],
        specs: [
          ['Includes', 'OpenFC-Lite-Mini + OpenESC (20×20)'],
          ['Mount', '20×20'],
          ['FC', 'OpenFC-Lite-Mini — RP2354A, QFN-60'],
          ['ESC', 'OpenESC 20×20 — DOY180N03T, 30 V / 1.0 mΩ'],
          ['Continuous', '30 A / channel — preliminary'],
        ],
      },
      '30×30': {
        tagline: 'OpenFC-Lite + OpenESC 30×30 — 5", freestyle.',
        highlights: [
          ['Pair', 'FC-Lite + ESC 30×30'],
          ['Mount', '30.5×30.5'],
          ['Continuous', '50 A / channel'],
        ],
        specs: [
          ['Includes', 'OpenFC-Lite + OpenESC (30×30)'],
          ['Mount', '30.5×30.5'],
          ['FC', 'OpenFC-Lite — RP2354, 30.5×30.5'],
          ['ESC', 'OpenESC 30×30 — SP40N01GHNK, 40 V / 1.2 mΩ'],
          ['Continuous', '50 A / channel — preliminary'],
        ],
      },
    },
    bundle: {
      components: [
        {
          title: 'OpenFC-Lite',
          handle: 'openfc-lite',
          firmware: 'Betaflight',
          firmwareUrl: 'https://github.com/betaflight/betaflight',
          blurb:
            'RP2354 dual-core M33 running Betaflight: 6-axis IMU, microSD blackbox, PIO-driven analog OSD (in development) and a switchable 10 V VTX rail. No onboard radio — bring your own RX over UART.',
        },
        {
          title: 'OpenESC',
          handle: 'openesc',
          firmware: 'AM32',
          firmwareUrl:
            'https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware',
          blurb:
            'Four AT32F421 channels, NSG2065Q gate drivers, INA186A3 + 0.2 mΩ current sensing. Same 20×20 / 30×30 mount options as OpenFC-Lite, so the pair stacks.',
        },
      ],
    },
  },
};

/** Fallback when a handle has no editorial content yet. */
export const PRODUCT_CONTENT_FALLBACK: ProductContent = {
  fileNumber: '—',
  family: 'Product',
  hero: {
    line1: '',
    line2Italic: '',
    line3: '',
    lead: '',
  },
  firmware: {project: ''},
  repoUrl: 'https://github.com/incutec-hw',
  inTheBox: [],
  downloads: [],
  specs: [],
};
