import {useEffect, useRef, useState} from 'react';

export type BoardArtProps = {
  /** Public path to the layered SVG, e.g. /boards/openesc/board.svg */
  src: string;
  /** Optional handle used for analytics / data attributes. */
  handle?: string;
  /** Optional "Inspect interactively" deep-dive link (e.g. KiCanvas hosted). */
  inspectUrl?: string;
};

/**
 * Render a layered board SVG as a scroll-revealed blueprint.
 *
 * The asset is generated by scripts/export-board-art.mjs and is a single
 * SVG with `<g id="layer-{copper,mask,silk,edge-cuts}">` children. We
 * fetch it lazily (only when the section approaches the viewport), drop
 * it inline so CSS can address each layer, and toggle `.is-revealed`
 * to kick off the entrance animation defined in app.css.
 */
export function BoardArt({src, handle, inspectUrl}: BoardArtProps) {
  const ref = useRef<HTMLDivElement | null>(null);
  const [svg, setSvg] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [failed, setFailed] = useState(false);
  const [side, setSide] = useState<'top' | 'bottom'>('top');

  useEffect(() => {
    const el = ref.current;
    if (!el || typeof IntersectionObserver === 'undefined') return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            io.disconnect();
            fetch(src)
              .then((r) => (r.ok ? r.text() : Promise.reject(r.status)))
              .then((text) => {
                setSvg(text);
                // Give the browser a frame to paint the SVG before
                // flipping the class — otherwise the transition is
                // missed and the layers pop in instantly.
                requestAnimationFrame(() =>
                  requestAnimationFrame(() => setRevealed(true)),
                );
              })
              .catch(() => setFailed(true));
            return;
          }
        }
      },
      {rootMargin: '400px 0px', threshold: 0.01},
    );
    io.observe(el);
    return () => io.disconnect();
  }, [src]);

  return (
    <div
      ref={ref}
      className={`board-art${revealed ? ' is-revealed' : ''}`}
      data-board={handle}
      data-side={side}
    >
      <div
        className="board-art-canvas"
        aria-hidden="true"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={svg ? {__html: svg} : undefined}
      />
      {svg && !failed ? (
        <div className="board-art-toggle" role="group" aria-label="Board side">
          <button
            type="button"
            className={side === 'top' ? 'is-active' : undefined}
            aria-pressed={side === 'top'}
            onClick={() => setSide('top')}
          >
            Top
          </button>
          <button
            type="button"
            className={side === 'bottom' ? 'is-active' : undefined}
            aria-pressed={side === 'bottom'}
            onClick={() => setSide('bottom')}
          >
            Bottom
          </button>
        </div>
      ) : null}
      {failed ? (
        <p className="board-art-fallback">
          Board art unavailable.{' '}
          {inspectUrl ? (
            <a href={inspectUrl} target="_blank" rel="noopener noreferrer">
              Open on KiCanvas ↗
            </a>
          ) : null}
        </p>
      ) : null}
      {inspectUrl ? (
        <a
          className="board-art-inspect"
          href={inspectUrl}
          target="_blank"
          rel="noopener noreferrer"
        >
          Inspect interactively ↗
        </a>
      ) : null}
    </div>
  );
}
